perfiles/urls.py
from django.urls import path
from post.views import *
from perfiles.views import BlogLogin, BlogLogout, BlogSignUp, ProfileUpdate, ProfileBorrar, ProfileList, DetailUser

urlpatterns = [
    path('profile/', ProfileList.as_view(), name="user-list"), 
    path('user-profile/<int:pk>/borrar/', ProfileBorrar.as_view(), name="profile-borrar"),
    path('user-profile/<int:pk>', ProfileUpdate.as_view(), name="profile-update"),
    path('detail/<int:pk>/', DetailUser.as_view(), name="profile-detail"),
    path('login/', BlogLogin.as_view(), name="blog-login"),
    path('logout/', BlogLogout.as_view(), name="blog-logout"),
    path('signup/', BlogSignUp.as_view(), name="blog-signup"),
]

post/urls.py
from django.urls import path
from post.views import *
from post.views import PostList, CreatePost, DetailPost, UpdatePost, DeletePost, SearchPostByname

urlpatterns = [
    path('list/', PostList.as_view(), name="blog-list"),
    path('create/', CreatePost.as_view(), name="blog-crear"),
    path('detail/<int:pk>/', DetailPost.as_view(), name="blog-detail"),
    path('update/<int:pk>/', UpdatePost.as_view(), name="blog-actualizar"),
    path('delete/<int:pk>', DeletePost.as_view(), name="blog-borrar"),
    path('search-by-name/', SearchPostByname.as_view(), name="search-by-name-post"),
]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from blog.views import Home, Blogs, Error404View, Contacto
from django.conf.urls import handler404
from blog.views import CreateComentario, ComentarioList

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Home, name='pagina-principal'),
    path('contact/', Contacto.as_view(), name="contacto"),
    path('pages/', Blogs, name="index-blog"),
    path('accounts/', include('perfiles.urls')),
    path('pages/', include('post.urls')),
    path('comentario/', CreateComentario.as_view(), name="crear-comentario"),
    path('about/', ComentarioList.as_view(), name="nosotros"),
]

handler404 = Error404View.as_view()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

class Contacto(models.Model):
    nombre = models.CharField(max_length=20)
    correo = models.EmailField(max_length=50)
    numero_telefono = models.CharField(max_length=20)
    mensaje = models.TextField(max_length=2000)
    fecha = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"ID: {self.id} | Nombre: {self.nombre} | Fecha: {self.fecha}"

class Comentario(models.Model):
    nombre = models.CharField(max_length=20)
    mensaje = models.TextField(max_length=2000)
    fecha = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"ID: {self.id}, Nombre: {self.nombre}, Fecha: {self.fecha}"

perfiles/models.py
from django.db import models

post/models.py
from django.db import models
from django.contrib.auth.admin import User

class Post(models.Model):
    autor = models.ForeignKey(User, on_delete=models.CASCADE)
    titulo = models.CharField(max_length=30)
    sub_titulo = models.CharField(max_length=100)
    cuerpo = models.TextField(max_length=2000)
    fecha = models.DateTimeField(auto_now_add=True)
    imagen = models.ImageField(upload_to="imagenpost", null=True, blank=True)

    def __str__(self):
        return f"ID: {self.id}, Titulo: {self.titulo}, Autor: {self.autor}"

blog/forms.py
from django.forms import ModelForm
from blog.models import Comentario

class ComentarioForm(ModelForm):
    class Meta:
        model = Comentario
        fields = ('nombre', 'mensaje')

perfiles/forms.py
from django import forms  
from django.contrib.auth.models import User  
from django.contrib.auth.forms import UserCreationForm
from django.forms.fields import EmailField   
from django.core.exceptions import ValidationError
from django.forms.forms import Form 

class CustomUserCreationForm(UserCreationForm):  
    username = forms.CharField(label='username', min_length=5, max_length=150)  
    email = forms.EmailField(label='email')  
    password1 = forms.CharField(label='password1', widget=forms.PasswordInput)  
    password2 = forms.CharField(label='password2', widget=forms.PasswordInput)  
  
    def email_clean(self):  
        email = self.cleaned_data['email'].lower()  
        new = User.objects.filter(email=email)  
        if new.count():  
            raise ValidationError("El correo ya esta en uso")  
        return email  

    def save(self, commit = True):  
        user = User.objects.create_user(  
            self.cleaned_data['username'],  
            self.cleaned_data['email'],  
            self.cleaned_data['password1'],
        )  
        return user  

blog/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView
from blog.models import Contacto, Comentario
from post.models import Post
from django.views.generic import ListView, CreateView
from blog.forms import ComentarioForm

def Home(request):
    return render (request, "blog/index.html")

class Contacto(CreateView):
    model = Contacto
    fields = ['nombre', 'correo', 'numero_telefono', 'mensaje']
    success_url = reverse_lazy("pagina-principal")

@login_required
def Blogs(request):
    posts = Post.objects.order_by('-fecha').all()
    return render(request, 'blog/blogs.html', {"post":posts})

class Error404View(TemplateView):
    template_name = "blog/error_404.html"

class ComentarioList(ListView):
    model = Comentario

class CreateComentario(CreateView):
    model = Comentario
    fields = ['nombre', 'mensaje']
    success_url = reverse_lazy("nosotros")

perfiles/views.py
from .forms import CustomUserCreationForm
from django.contrib.auth import forms  
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.admin import User
from django.views.generic import ListView, CreateView, DeleteView, UpdateView, DetailView
from django.urls import reverse_lazy

class BlogLogin(LoginView):
    template_name = 'perfiles/blog_login.html'
    next_page = reverse_lazy("index-blog")

class BlogLogout(LogoutView):
    template_name = 'perfiles/blog_logout.html'

class BlogSignUp(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy("blog-login")
    template_name = "registration/signup.html"

class ProfileList(LoginRequiredMixin, ListView):
    model = User

class ProfileBorrar(LoginRequiredMixin, DeleteView):
    model = User
    success_url = reverse_lazy("user-list")

class ProfileUpdate(LoginRequiredMixin, UpdateView):
    model = User
    fields = ['username', 'first_name', 'last_name', 'email']
    success_url = reverse_lazy("blog-login")

class DetailUser(LoginRequiredMixin, DetailView):
    model = User

post/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DeleteView, UpdateView, DetailView
from post.models import Post

class PostList(LoginRequiredMixin, ListView):
    model = Post

class CreatePost(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['autor', 'titulo', 'sub_titulo', 'cuerpo', 'imagen']
    success_url = reverse_lazy("blog-list")

class DetailPost(LoginRequiredMixin, DetailView):
    model = Post

class UpdatePost(LoginRequiredMixin, UpdateView):
    model = Post
    fields =['autor', 'titulo', 'sub_titulo', 'cuerpo', 'imagen']
    success_url = reverse_lazy("blog-list")

class DeletePost(LoginRequiredMixin, DeleteView):
    model = Post
    success_url = reverse_lazy("blog-list")

class SearchPostByname(ListView):
    def get_queryset(self):
        post_title = self.request.GET.get('post-titulo')
        return Post.objects.filter(titulo__icontains=post_title)

app1/templates/app1/interfaz.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="css/interfaz.css">
</head>
<body>
        <nav class="navbar navbar-expand-lg bg-light navbar-dark bg-dark">
            <div class="container-fluid">
              <a class="navbar-brand" href="#">Navbar</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Home</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">Features</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">Pricing</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">Pricing</a>
                  </li>
                </ul>
              </div>
            </div>
          </nav>
    <div class="container">

    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js" integrity="sha384-IDwe1+LCz02ROU9k972gdyvl+AESN10+x7tBKgc9I5HFtuNz0wWnPclzo6p9vxnk" crossorigin="anonymous"></script>
</body>
</html>

blog/templates/blog/about.html
{% extends 'blog/base.html' %}
{% block nav %}{% endblock %}
{% block contenido %}
{% load static %}
        <!-- Page Header-->
        <header class="masthead" style="background-image: url('{% static 'blog/assets/img/b.jpg' %}');">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="page-heading">
                            <h2>{{configabout.titulo}}</h2>
                            <span>{{configabout.sub_titulo}}</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Main Content-->
        <main class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <p>Ezequiel Bosco 23 años de Castelar provincia de Buenos Aires y Esteban Santillán 28 años de Luján provincia de Buenos Aires,
                            dos estudiantes argentinos que estudiaron en coderhouse te cuentan sobre su blog. </p>
                        <p>Creamos Codeo Blog para vos, para que te acompañe en tus dudas y puedas potenciar tus conocimientos.</p>
                        <p>El lenguaje de programacion es el motor para el mundo de la tecnologia que avanza cada dia mas.</p>
                        <p>Fundamos este blog para que no bajes los brazos y que no te vayas sin poder resolver tus dudas con la ayuda de todos.</p>
                        <p>Queremos que la gente cree debates, muestre diferentes opiniones sobre los temas a publicar y lo más importante, formar una comunidad.</p>
                    </div>
                </div>
            </div>
        </main>

{% endblock %}

blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Blog programación</title>
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'blog/css/styles.css' %}" rel="stylesheet" />
    </head>
    {% block nav %}{% endblock %}
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <h3><a class="navbar-brand px-lg-1 py-3 py-lg-4" href="{% url 'pagina-principal' %}">Codeo Blog</a></h3>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'index-blog' %}">Blogs</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'nosotros' %}">Acerca de nosotros</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'contacto' %}">Contacto</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blog-login' %}">Iniciar sesión</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blog-signup' %}">Registrarme</a></li>
                    </ul>
                </div>
            </div>
        </nav> 
        {% block contenido %}{% endblock %}
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-10">
                <div class="row gx-4 gx-lg-10 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-11">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="https://github.com/EzequielBosco/Proyecto_final_Coderhouse">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                    <div class="small text-center text-muted fst-italic">GitHub</div>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Desarrollado por &copy; Codeo Blog Web 2022</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>

blog/templates/blog/blogs.html
{% extends 'blog/base.html' %}
{% block nav %}{% endblock %}
{% block contenido %}
{% load static %}
        <!-- Page Header-->
        <header class="masthead" style="background-image: url('{% static 'blog/assets/img/f.jpg' %}');">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h2>Blogs</h2>
                            <span>Blogs de la comunidad</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Main Content-->
        <div class="container px-1 px-lg-4 col-lg-10">
            <p>Navega por los Blogs de la comunidad, <a href="{% url 'blog-crear' %}">Creá tu propio Blog</a> o ingresa lo que más te interese en el buscador</p>
        </div>
        <div class="container justify-content-center px-lg-1 col-lg-5">
        <div class="card mb-4 col-lg-8">
            <div class="card-header"><h5>Buscar</h5></div>
                <div class="card-body mb-10 px-lg-1 col-lg-10">
                <form action="{% url 'search-by-name-post' %}" method="get">
                    {% csrf_token %}
                    <input type="search" placeholder="Ingresa tu busqueda..." name="post-titulo">
                    <input class="btn-outline-dark flex-shrink-0" type="submit" value="Ir!">
                </form>     
                </div>
            </div> 
        </div>
        <!-- Divider-->
        <hr class="my-4" />
        </div>
        <div class="container col-md-3 col-lg-4 col-xl-3">
        <h3>Última publicación</h3>
        </div>
                    <!-- Divider-->
                    <hr class="my-4" />
        <div class="container px-4 px-lg-8">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-8">
                    <!-- Post preview-->
                    {% if post.0 %}
                    <div class="post-preview card h-15">
                        {% if  post.0.imagen %}
                        <a href="{% url 'blog-detail' post.0.id %}"><img style="max-width:100%;" class="card-img-top" src="{{ post.0.imagen.url }}"/></a>        
                        {% endif %}
                        <a href="{% url 'blog-detail' post.0.id %}"><h2 class="post-title">{{post.0.titulo}}</h2></a>
                        <span class="post-subtitle">{{post.0.sub_titulo}}</span>
                        <p class="post-meta">
                            Creado por 
                            <a href="{% url 'user-list' %}">{{post.0.autor}}</a> el {{post.0.fecha}}
                            <a class="btn btn-outline-dark flex-shrink-0" id="submitButton" type="submit" href="{% url 'blog-detail' post.0.id %}">Leer más →</a>
                        </p>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
        <!-- Divider-->
        <hr class="my-4" />
        <div class="container col-md-4 col-lg-4 col-xl-4">
        <h3>Publicados recientemente</h3>
        </div>
        <!-- Divider-->
        <hr class="my-4" />
        <div class="container">
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-2 row-cols-xl-2 justify-content-center">
            <div class="col mb-5">
                    {% if  post.1 %}
                    <!-- Post preview-->
                    <div class="card h-100">
                        {% if  post.1.imagen %}
                        <a href="{% url 'blog-detail' post.1.id %}"><img style="max-width:100%;" class="card-img-top" src="{{ post.1.imagen.url }}"/></a>
                        {% endif %}
                        <a href="{% url 'blog-detail' post.1.id %}"><h2 class="post-title">{{post.1.titulo}}</h2></a>
                        <span class="post-subtitle">{{post.1.sub_titulo}}</span>
                    <p class="post-meta">
                        Creado por
                        <a href="{% url 'user-list' %}">{{post.1.autor}}</a> el {{post.1.fecha}}
                        <div class="container text-center">
                            <a class="btn btn-outline-dark flex-shrink-0" id="submitButton" type="submit" href="{% url 'blog-detail' post.1.id %}">Leer más →</a>
                        </div>
                        </p>
                    </div>
                    {% endif %}
            </div>
            <div class="col mb-5">
                    {% if  post.2 %}
                    <!-- Post preview-->
                    <div class="card h-100">
                        {% if  post.2.imagen %}
                        <a href="{% url 'blog-detail' post.2.id %}"><img style="max-width:100%;" class="card-img-top" src="{{ post.2.imagen.url }}"/></a>
                        {% endif %}
                        <a href="{% url 'blog-detail' post.2.id %}"><h2 class="post-title">{{post.2.titulo}}</h2></a>
                        <span class="post-subtitle">{{post.2.sub_titulo}}</span>
                        <p class="post-meta">
                            Creado por
                            <a href="{% url 'user-list' %}">{{post.2.autor}}</a> el {{post.2.fecha}}
                            <div class="container text-center">
                                <a class="btn btn-outline-dark flex-shrink-0" id="submitButton" type="submit" href="{% url 'blog-detail' post.2.id %}">Leer más →</a>
                            </div>
                        </p>
                    </div>
                    {% endif %}
            </div>
                    {% if  post.3 %}
                    <!-- Post preview-->
                    <div class="card h-100">
                        {% if  post.3.imagen %}
                        <a href="{% url 'blog-detail' post.3.id %}"><img style="max-width:100%;" class="card-img-top" src="{{ post.3.imagen.url }}"/></a>
                        {% endif %}
                        <a href="{% url 'blog-detail' post.3.id %}"><h2 class="post-title">{{post.3.titulo}}</h2></a>
                        <span class="post-subtitle">{{post.3.sub_titulo}}</span>
                        <p class="post-meta">
                            Creado por
                            <a href="{% url 'user-list' %}">{{post.3.autor}}</a> el {{post.3.fecha}}
                            <div class="container text-center">
                                <a class="btn btn-outline-dark flex-shrink-0" id="submitButton" type="submit" href="{% url 'blog-detail' post.3.id %}">Leer más →</a>
                            </div>
                        </p>
                    </div>
                    {% endif %}
            <div class="col mb-5">
                    {% if  post.4 %}
                    <!-- Post preview-->
                    <div class="card h-100">
                        {% if  post.4.imagen %}
                        <a href="{% url 'blog-detail' post.4.id %}"><img style="max-width:100%;" class="card-img-top" src="{{ post.4.imagen.url }}"/></a>
                        {% endif %}
                        <a href="{% url 'blog-detail' post.4.id %}"><h2 class="post-title">{{post.4.titulo}}</h2></a>
                        <span class="post-subtitle">{{post.4.sub_titulo}}</span>
                        <p class="post-meta">
                            Creado por
                            <a href="{% url 'user-list' %}">{{post.4.autor}}</a> el {{post.4.fecha}}
                            <div class="container text-center">
                                <a class="btn btn-outline-dark flex-shrink-0" id="submitButton" type="submit" href="{% url 'blog-detail' post.4.id %}">Leer más →</a>
                            </div>
                        </p>
                    </div>
                    {% endif %}
            </div>
                    {% if  post.5 %}
                    <!-- Post preview-->
                    <div class="card h-100">
                        {% if  post.5.imagen %}
                        <a href="{% url 'blog-detail' post.5.id %}"><img style="max-width:100%;" class="card-img-top" src="{{ post.5.imagen.url }}"/></a>
                        {% endif %}
                        <a href="{% url 'blog-detail' post.5.id %}"><h2 class="post-title">{{post.5.titulo}}</h2></a>
                        <span class="post-subtitle">{{post.5.sub_titulo}}</span>
                        <p class="post-meta">
                            Creado por
                            <a href="{% url 'user-list' %}">{{post.5.autor}}</a> el {{post.5.fecha}}
                        <div class="container text-center">
                            <a class="btn btn-outline-dark flex-shrink-0" id="submitButton" type="submit" href="{% url 'blog-detail' post.5.id %}">Leer más →</a>
                        </div>
                        </p>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
        </div>
        <!-- Divider-->
        <hr class="my-4" />
        <div class="container text-center">
            <p><a href="{% url 'blog-logout' %}" class="btn btn-outline-dark flex-shrink-0">Salir de la sesión</a> | <a href="{% url 'profile-update' user.id %}">Actualizar usuario </a> | <a class="btn btn-outline-dark flex-shrink-0" id="submitButton" type="submit" href="{% url 'user-list' %}">   Lista de Usuarios</a></p>
        </div>
{% endblock %}

blog/templates/blog/comentario_form.html
{% extends 'blog/base.html' %}
{% block nav %}{% endblock %}
{% block contenido %}
{% load static %}
        <!-- Page Header-->
        <header class="masthead" style="background-image: url('{% static 'blog/assets/img/f.jpg' %}');">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="page-heading">
                            <h2>Crear comentario</h2>
                            <span></span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Main Content-->
        <main class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <p></p>
                        <div class="my-5">
                            <form id="contactForm" method="post">
                                {% csrf_token %}
                                <div class="form">
                                {{ form.as_p }}
                                </div>
                                <!-- Submit Button-->
                                <input class="btn btn-outline-dark flex-shrink-0" type="submit" value="Enviar">
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </main>
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
{% endblock %}

blog/templates/blog/contacto_form.html
{% extends 'blog/base.html' %}
{% block nav %}{% endblock %}
{% block contenido %}
{% load static %}
        <!-- Page Header-->
        <header class="masthead" style="background-image: url('{% static 'blog/assets/img/b.jpg' %}');">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="page-heading">
                            <h2>Contactanos</h2>
                            <span>¿Tenes una duda? Nosotros te la respondemos</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Main Content-->
        <main class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <h5>¿Querés ponerte en contacto?</h5>
                        <p>Completa el formulario para que podamos comunicarnos lo más rápido posible!</p>
                        <div class="my-5">
                            <form id="contactForm" data-sb-form-api-token="API_TOKEN" form  enctype='multipart/form-data' method="post">
                                {% csrf_token %}
                                <div class="form-floating">
                                <p>
                                    <label for="id_nombre">Nombre</label>
                                        <input type="text" name="nombre" class="form-control" maxlength="20" placeholder="Ingrese su nombre..." autofocus="" required="" id="id_nombre">
                                </p>
                                <p>
                                    <label for="id_correo">Correo</label>
                                    <input type="email" name="correo" class="form-control" placeholder="Ingrese su correo..." required="" data-sb-validations="required,email" id="id_correo">
                                </p>
                                <p>
                                <label for="id_numero_telefono">Número de Teléfono</label>
                                <input type="tel" name="numero_telefono" class="form-control" placeholder="Ingrese su número de teléfono..." required="" id="id_numero_telefono">
                                </p>
                                <p>
                                <label for="id_mensaje">Mensaje</label>
                                <textarea type="text" name="mensaje" class="form-control" style="height: 10rem" placeholder="Ingrese su mensaje..." required="" id="id_mensaje"></textarea>
                                </p>
                            </div>
                                <!-- Submit Button-->
                                <input class="btn btn-outline-dark flex-shrink-0" type="submit" value="Enviar">
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </main>
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
{% endblock %}

blog/templates/blog/error_404.html
{% extends 'blog/base.html' %}
{% block nav %}{% endblock %}
{% block contenido %}
{% load static %}
        <!-- Page Header-->
        <header class="masthead" style="background-image: url('{% static 'blog/assets/img/e.jpg' %}');">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h4>La página ingresada no existe</h4>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <div class="container text-center">
            <a id="submitButton" type="submit" class="btn btn-outline-dark flex-shrink-0" href="{% url 'pagina-principal' %}">Volver al inicio</a>
        </div>
{% endblock %}